---
services:
  zulip:
    image: ghcr.io/zulip/zulip-server:latest
    profiles: [apps, utils, all]
    networks: ["traefik_public"]
    # ports:
    #   - "5501:3000"
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
    volumes: [zulip-cache:/zulip/cache]
    labels:
      # - sablier.enable=true
      # - sablier.group=zulip
      - homepage.group=Utilities
      - homepage.name=Zulip
      - homepage.icon=zulip-web.png
      - homepage.href=https://zulip.${DOMAIN:-traefik.me}
      - homepage.description=Asynchronous chat app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
networks:
  traefik_public:
    name: traefik_public
    driver: bridge
    attachable: true
volumes:
  zulip-cache:

##############################

# Further setup needed before deployment:
# https://zulip.readthedocs.io/projects/docker/en/latest/how-to/compose-getting-started.html


##############################