---
http:
  routers:
    budget:
      rule: Host(`budget.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: budget
      middlewares: [sablier-budget@file, startup-retry@file]
  services:
    budget:
      loadBalancer:
        servers:
          - url: http://budget:5006/
  middlewares:
    sablier-budget:
      plugin:
        sablier:
          group: budget
          dynamic:
            displayName: Budget
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
