---
http:
  routers:
    joplin:
      rule: Host(`joplin.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: joplin
      middlewares: [sablier-joplin@file, startup-retry@file]
  services:
    joplin:
      loadBalancer:
        servers:
          - url: http://joplin:22300/
  middlewares:
    sablier-joplin:
      plugin:
        sablier:
          group: joplin
          dynamic:
            displayName: Joplin
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m